In [13]:
class car():
    def __init__(self):
        self.color()
        self.model()
        self.year()
    def color(self):
        print('blue')
    def model(self):
        print('bmw')
    def year(self):
        print('2017')
ca=car

In [14]:
class Friend:
    def __init__(self):
        self.job="None"
    
    def getjob(self):
        return self.job
    
    def setjob(self,job):
        self.job=job
        
kalai=Friend()
prabs=Friend()
pavi=Friend()

kalai.setjob("Designer")
prabs.setjob("Professor")
pavi.setjob("Teacher")

print(prabs.job)
print(kalai.job)
print(pavi.job)

Professor
Designer
Teacher


In [17]:
class Kurti:
    def material(self):
        print('material')
        
class Tops(Kurti):
    def brand(self):
        print('fabric')

Kurti=Tops()
Kurti.material()
Kurti.brand()

material
fabric


In [24]:
class chocolate:
    name=""
class brand:
    types=2
class flavour(chocolate,brand):
    version=3
obj=flavour()
obj.name="chokichoki"

print(obj.name)
print(obj.types)
print(obj.version)

chokichoki
2
3


In [28]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3],[1,2,3,4]])
d=np.array([[[1,2,3],[5,6,7],[2,6,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
1
2


/var/folders/bs/wq_0zmxs14l_wf2ts_fyt1pm0000gp/T/ipykernel_68220/1906401853.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[1,2,3],[1,2,3,4]])
/var/folders/bs/wq_0zmxs14l_wf2ts_fyt1pm0000gp/T/ipykernel_68220/1906401853.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d=np.array([[[1,2,3],[5,6,7],[2,6,8,9]]])


In [29]:
arr=np.array([1,2,3])
print(arr[0])

1


In [32]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [35]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
arr=np.array([[1,2,3,4],[7,8,9,10]])
newarr=arr.reshape(-1)
print(newarr)

[ 1  2  3  4  7  8  9 10]


In [37]:
arr=np.array([[1,2],[3,4]])
for x in arr:
    print(x)

[1 2]
[3 4]


In [40]:
arr1=np.array([1,2])
arr2=np.array([3,4])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4]


In [15]:
class car():
    def __init__(self):
        self.color()
        self.model()
        self.year()
    def color(self):
        print('blue')
    def model(self):
        print('bmw')
    def year(self):
        print('2017')
ca=car

In [4]:
import numpy as np
arr = np.array([[1,2,3],[6,7,8],[5,6,2]])
print(arr)
print(np.amin(arr))
print(np.amax(arr))


[[1 2 3]
 [6 7 8]
 [5 6 2]]
1
8


In [6]:
import numpy as np
a = np.array([[11,15,20]])
print(a)
print(np.mean(a))

[[11 15 20]]
15.333333333333334


In [7]:
import numpy as np
a = np.array([[11,15,20]])
print(a)
print(np.median(a))

[[11 15 20]]
15.0


In [8]:
import numpy as np
a = np.array([[11,15,20]])
print(a)
print(np.average(a))

[[11 15 20]]
15.333333333333334


In [10]:
import numpy as np
a = np.array([[11,15,20]])
print(a)
print(np.var(a))

[[11 15 20]]
13.555555555555555


In [13]:
import numpy as np
a = np.array([[11,15,20]])
print(a)
print(np.percentile(a,15,20))

[[11 15 20]]


AxisError: axis 20 is out of bounds for array of dimension 2